Added tx-id to schema
trufflesuite/truffle-contract-schema pull request #19
Opened 2017-11-23 00:25 UTC by kingcocomango

Part of three PRs for https://github.com/trufflesuite/truffle/issues/472

2017-11-23 15:53 UTC, stevejaxon commented
A neater solution would probably be to pull out the regex for the TXhash into a property and reference that in the two places in the schema rather than duplicate the regexp:

`
"transactionId": {
      "type": "string",
      "pattern": "^0x[a-fA-F0-9]{64}$"
    },
`
...
`
"patternProperties": {
        "^0x[a-fA-F0-9]{64}$": { "$ref": "abi.spec.json#/definitions/Event" }
      },
`

More in line with what is done for the address: 
`
"address": { "$ref": "#/definitions/Address" },
`

2017-12-21 02:06 UTC, gnidan requested changes
This looks great! Mind updating the PR with two small things? Looks good to merge after that.

2017-12-21 02:06 UTC, gnidan commented on package.json
> -  "version": "1.0.0",
Mind removing the version bump? That part's done as part of our releases

2017-12-21 02:06 UTC, gnidan commented on spec/network-object.spec.json
> +    "Transaction": {
Since I've already asked for one change :)

Let's call this "class" `TransactionID` just for the sake of explicitness (and update on L9)

2018-01-02 19:38 UTC, gnidan approved these changes
Looks good. Thanks!

2018-02-16 18:42 UTC, merged